language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: lKhk6hDZFvhNiDxbyt3B64V4PnsjM7biCF6ZEtE3Jt6INf4FAOG0WTDvwuVpVdf/zvA/bhn9HqtcDittjyRCFMHBemLKKP+A57jgSb4i0Z7pMphP0jLOuvZg1P0M9iM+FTdUXcaLHu72Qi6EcPjqG1J1QzNe6rf+B+ZBLf/H2IpGWVCdLCJYI0y2D/DdW4MEUAsUUEb4wsQcmSV8hWGyISCOgPNjbkayPUkI6OKnzwwFggP5qwOyqbeYTHvKcubWaZkHh4YStjUqwozuss879KN2qH/oO5GFyDQUV3yF/rXftzMSs0t3cKx5MSAdXi7FKq/w63bxhXCAiANBkXcXInOoMfQWv5QxfGWsmn69e0SS1mpEVHq0CVzj0blBahUdwI8cnZ8RE0ytja/SMe+AtpYUSZfrcA0hwV+sqMkrVNVAxerkebLbPSM8fMSFhAfQpnHs119fLl/ETTyjj9Q2uy3B4wSXCZdCBVpqms3F2k/v8DFz23Ovg70WNCccKhVdiZI7dfdZgMPnw+rVj6gzUddOzXKNR8AKDjED0muiGwnRAESxybhu4lOL/0dABsFQ50sYB/98Z6WG7yBu7quhJ0PNTm0l2mwLErL314hLRYBJCaptgP6SE/Rw6OeX9g7loDBTts7+sBA8dM2NI9Ucc5ObaJQnP07DQM2efUuXaok=
  - secure: Vc2OmbljGDScmtjdxtJU6YDyM8cbaI8ihRM0mwH90DXybtL+NCsQ4UOUXVrRUNXPGkCvUSmUzCCjdiMh+vEC8BneKa8k0MyIde81ye4UkiFKw3QY/XElcY/rt/RFnSwJheKbjf8ZE4RLQCGd8TRuweV9HOQlIpx8uYi3iIUZnw8aP4+VRFtTa6VLspblZtYmqNgmEreBAWwM8VqJ4S44emBtfQHq7eHyla8F65oJlq98vnm40A3R+MgqMpsOfbOwWG6kelJH9gsO2mZKmY0qxHrKrZaLw+8czCb/H7v9kkN8JOoTvnH2Ufv7i2IC0k47pSKjOYdnTUOf5Z2+/6gfJUECMVfMv2EE4je89sw/u21dNJluKfp5wqEiquyZfnK2jFF2T8Zfz24DnNYqh7lIjtmkWpINKQiTRV35yDorB3qqTrMojlJKgSkGwgYGdfOPQhqp2IqrWYYWnDXnX0RdCjwnDhLruSS/tTvUFJ+9aHuPah/wMEGzz0D1wFwe01JfjxxtGuDlEHFyeoD/xPzYOM9bkL7IivTY2ReSRLnY1/42KDEa7SYKlCUC6KleWeSvq2HRA1A3IPMCHInQKe9xlXjvdZDP4Lkj1Na6FdCQwYXmvXD5WJXSjWAMLw0l23c9GS1DMsrESgXEx9EVm46fXz/14XHu8cDIab9UGzB8CtE=
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 120s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: bundle exec s3_website push