language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
install: gem install jekyll html-proofer
script: bundle exec jekyll build
deploy:
  provider: azure_web_apps
