language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 120s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href --external_only --only-4xx --http-status-ignore 429
deploy:
  provider: s3
  access_key_id:
    secure: uRRG1iP5N17cmh93LmB1+UJeswlQcbwbB1S+O3bZpl5vTudFVft4QiZ5YwaecR6ZjSGbo0x9MeCAua2jtnqEKSXkN0PyFMN3AeajTcJvU487iDcABRRsykipceLBo/iROP23hp8ImkHlsWqexmJFZu/9S4jk4uzfQBOHR93bc1U+31ICYO0KMODvo32FwpU8kWxFbLqGYNta/0jmF6+hq2yKIpbmlEg9AVYDtZvlwLAkZAY0nwcgkzMBqvX+9VBiNEiCvBQsq64ETA7S6eAetm10PNZMQ/x6EvHLVSVsJSGKjY0gonv1Ojw51uugd+4ERm5GsbCGr5ntQD8T4/tuKU0ezTBS96rKkLSyu/enj8GlzzPIbjOpzqsKMhdJDe0ClgQrlvQMR2+n6gGygKaYU/pdv2tDy33y76s6j05KHi+TNmqWFcrEekDiSmb1+gg00U/RxDUHBPmTvsntJ6KpKQAA8gGEY1jnmnSMKUCZC8UGddoaN3DNfn9bsRuRFXtOS1eGpPRkef5/FBk0htre5Jjuw71tWNnK+d5H3BQsl9hhOMih8jEHeuJ0UoWatT/OyV02T3aLlxXTvELGGkkB/LCoiPbuu8pLGOPbcckK2ijux6ZLo3sm2vePjpULqq/2xoVVm6Dq5fu7qJfNazqDKDlQ+cZ66f7n5bDIXz5fo34=
  secret_access_key:
    secure: WN2lWND3tJxzMHw29FajW7fk1022Bio7k0pk8pSGTkDzUW1Eb1I0WTX6Ydm0DEYlrrq/mBe7qzxNo6Z1O/rD7hmWZEL3kvttDyy7oY3F2QX+jaKx8vQlQ9HZhl7PvVgT5NOwip4nrfOszJFeFbSbNDC3njMJyz8Yawz6HDM4q9out8Qt0bZFwhvTRmtAZ4PwcZhgoQg7+duT2yyN5QilcaGyeQdJrCgnPETbhwN3PXavmH1cIHBmIma2OcG6rVtPvXg7gunvvQrH070DahKwMi0oFgDqsn10WIjjzDr07nFMdufu2Cobb8EyMQZUBZtLpw6x95xHWLON1WoteINgORADwXt4GTuGjYORHSo12vyUET11VTNDiThio8RU8rQv9Xh4GlTkdFzDAJkCdnxTrbgUlm9ymbLWSwk5JEqL/X18HNKARjvNSRbwUaYPzyGgVjhWFXtUI4nt8OFnUOr2t4Pr5AMVc6a8ZGZzFQvKpx3uu68vi7FxWYKmbk1MyAe1EDtnbVnAgqOWBO2rbkuePo2VloxAgxBPPmO+JucIIOstwW/RL1wIlV9VVO63E29BJW0LN+W+wJG0Xg3IIIFGk4gATujMmzJIPtSsOCHwj3qoK04Cr/Jb6w2NI6trfAZVrS0ZAiV1JJj8aLfkvvpNCMz40iykhS5QY9f9Vxh7FoU=
  bucket: tucla
  skip_cleanup: true
  local_dir: _site
  upload-dir: blog
